dmcontent/__init__.py
dmcontent/content_loader.py
tests/test_content_loader.py

[Original story](https://www.pivotaltracker.com/story/show/122114497) was a small content change however the only way to do it was to introduce filtering descriptions by lot to the content loader (for which [this new story](https://www.pivotaltracker.com/story/show/126772043) was added).
First, a YAML schema was decided and added to the frameworks repository. [This PR](https://github.com/alphagov/digitalmarketplace-frameworks/pull/293) includes full details of the new schema. Examples of new schema:
```
description: Buyers will use the information suppliers provide here to create a shortlist.
```
or 
```
description:
default: Buyers will use the information suppliers provide here to create a shortlist.
digital-specialists: You can only offer 1 specialist for this opportunity. Buyers will …
```

[126772043] Filter descriptions by lot

---

dmcontent/__init__.py
dmcontent/content_loader.py
tests/test_content_loader.py

Slugs are generally automatically generated, but in some cases (e.g. if there are extended unicode characters such as non-breaking hypens and spaces in the section name) we want to explicitly set a slug.

Allow slug to be set manually in content

---

CHANGELOG.md
dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/errors.py
dmcontent/messages.py
dmcontent/questions.py
dmcontent/utils.py
requirements.txt
tests/test_content_loader.py
tests/test_content_section.py
tests/test_messages.py
tests/test_questions.py
tests/test_utils.py

**Note:**
⚠️  This needs to come in at the same time as version 4.x.x of the frameworks repo. [PR here](https://github.com/alphagov/digitalmarketplace-frameworks/pull/326) ⚠️ 
***
Before, all values in YAML files were stored as strings and then printed out
directly by jinja in the frontend apps.  Now, we're creating [TemplateField](https://github.com/alphagov/digitalmarketplace-content-loader/blob/474d9adce0f422700cbf2dfc8815a7503ab368bc/dmcontent/utils.py#L8)s
for specific attibutes of questions and sections.  TemplateFields are wrappers
around jinja [Templates](http://jinja.pocoo.org/docs/dev/api/#jinja2.Template) that are passed an initial string and then are rendered
with a context.
The result of all this is that we can pass variables to our content which
come from briefs or lots or …

[#131733667] Content loader to support Jinja templating

---

dmcontent/__init__.py
dmcontent/messages.py
tests/test_messages.py

Content variation template uses a list of dictionaries for rendering framework agreement changes so we need to support arbitrary nesting of structures in ContentMessage.
The logic remains mostly the same:
* render simple fields right away
* wrap dictionaries with `ContentMessage`
* render/wrap all items inside a list individually

Add support for nested lists/dicts in ContentMessage list fields

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

In order to do nice-to-have questions with optional evidence
questions, we've created a new DynamicList question type.
1. `DynamicList` questions
`DynamicList` mostly works like a multiquestion, with a few key
differences:
- `.filter()` method merges its original templated questions with
brief data to generate new questions.  This means we can
leave a question's "question" field as "{{ item }}" and then
pass a string into it from a brief just before rendering it.
- `.filter()` method also rewrites question "id"s and "followup"s
with trailing index numbers.
eg `id: "yesno"` becomes `id: "yesno-0"` or whatever
- `.get_data()` method transforms data that comes back from
the form into something the API will understand, sanitizing
values and grouping related questions together.
eg `{"yesno-1": …

Add DynamicList question

---

dmcontent/__init__.py
dmcontent/content_loader.py
tests/test_content_loader.py

Will be used so we can iterate through questions, one per page, for the new brief response flow. Similar to the `manifest.get_next_section_id` method.
- Will return the id of the next question
- If no question_id provided will return the first question
- If last question_id provided will return `None`
- Will ignore any questions that are questions attributed to a multiquestion

Add `section.get_next_question_id` method

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

This method unpacks service data to be used in a form. Dynamic lists data is stored differently to that passed to a form and therefore requires manipulation from one key into several top level keys.
So we can call `unformat_data` from any question without having to worry about if it is a dynamic list or not I have also added a method to the parent `Question` class that will simply return the data passed in.

Add `unformat_data` method to `Question` and `DynamicListQuestion`

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

We want our question errors ordered by index. JSON schema errors on a list of objects should give us back our errors ordered by index. These errors are passed from the API to the content loader. Based on this assumption, we just need to maintain this order using an OrderedDict.

Return ordered dynamic list question errors

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

For [this pivotal story](https://www.pivotaltracker.com/story/show/133440815)
Our form data may include followup answers which are non empty (if the user says yes to the question, adds followup answer and then changes their mind and says no to the original question). This would mean that `False` would be sent with the follow up answer in the form data. We wish to strip out the follow up answer in this case when using `get_data` as it is redundant information.

Remove followup answers for False answer to dynamic list questions

---

dmcontent/__init__.py
dmcontent/content_loader.py
tests/test_content_loader.py

Essentially the opposite of `get_next_question_id` apart from the `question_id` argument is not optional as we assume no need to get the last question. Note, if this need does arise then this functionality can easily be added.

Add `get_previous_question_id` to `ContentSection` class

---

.travis.yml
requirements.txt
setup.py

* Remove `tests/*__init__.py` files to avoid tests being added by `find_packages` in `setup.py`.
* Add dependencies to `setup.py`
Explained in depth here:
https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1cQFNx4WEvI-IGZ1g9K8JtZfeplrEmoJbtBOOpaJSEdQ

NO-TICKET-specify-packages

---

dmcontent/__init__.py
dmcontent/content_loader.py
tests/test_content_loader.py

* Adds functionality to generate slugs for all (non-multiquestion) questions
* Adds get_next/previous_question_slug, based off get_next/previous_question_id (which should probably be removed in the future).
* Version bump to 2.6.0.

[194] One question per page

---

dmcontent/__init__.py
dmcontent/content_loader.py
tests/test_content_loader.py
tests/test_content_section.py

Story https://www.pivotaltracker.com/story/show/138702601
Really just followed the path of `editable`. Though noted that `editable` handling itself is a bit under-tested.

[#138702601]ContentSection: add prefill flag

---

dmcontent/__init__.py
dmcontent/content_loader.py
tests/test_content_loader.py

This was tripping up on (letting through) nbsp's.

slugification: handle unicode whitespace properly

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

- ticket https://www.pivotaltracker.com/n/projects/904880/stories/138703715
- requirement is to get 'readable' text, i.e. not rendered into HTML
- actually, the source can still contain HTML, as much HTML is valid
markdown, so this is really just a quick-fix

Add get_source attribute for the benefit of the CSV downloader.

---

CHANGELOG.md
dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/questions.py
dmcontent/utils.py
tests/test_content_section.py
tests/test_questions.py

Supports new followup YAML format.
Makes a separate _drop_followups method for the Multiquestions and
adds a call to it from `.get_data`.
It extends the method to support multi-input followup questions (eg
it should correctly drop all fields for a pricing followup), but it
still assumes that the original question data is stored in question
id key (which is true for most questions apart from multiquestions
and pricing, so they cannot have followups at the moment).
Schema generation calls `.filter` to create separate manifests for
separate framework lots, so that it can generate a schema for each
lot.
With the addition of DynamicList questions, filter now requires
dynamic data to generate the actual list of questions specific to
the brief, but that's not something we want to happen when …

Follow up questions

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

CheckboySummary currently displays the stored (internal) rather than translating it to the equivalent label.
This PR performs the translation of values->labels upon retrieval.

Checkbox summary values to equivalent labels

---

dmcontent/content_loader.py
dmcontent/questions.py
tests/test_content_loader.py

to allow caller to specify how it would like questions to be referred to in an error's "question" field.
Story https://www.pivotaltracker.com/story/show/141001837
This seemed to be the quickest most pragmatic way to enable me to fix this in the time permitted.

[#141001837]get_error_messages methods: add keyword argument question_descriptor_from

---

dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/questions.py
tests/test_questions.py

* Lot descriptions are currently stored in services/lots.yml for each framework, roughly working like a radios question.
* Descriptions for each possible choice are stored in options[x].description.
* Adds a TEMPLATE_OPTIONS_SUBFIELDS variable to Question to specify which subfields under options should be turned into TemplateFields and rendered appropriately.
* This check in options subfields does not iterate down beyond the first level, so will not work with - e.g. - CheckboxTree.

Add support for subfield TemplateFields

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_content_loader.py
tests/test_questions.py

The idea is that we should not have to repeat a standard error message in hundreds of question files, as we do at the moment.
Also added a full stop in the fallback error message, for consistency with the error messages we wrote into our YAML.

Specify a default error message for 'answer required'.

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

- https://trello.com/c/y79rP1KA/197-suppliers-choose-a-category-backend
- implements 'decision re validation / parent categories' (see ticket)

No longer persist parent values in the checkbox tree to the API.

---

dmcontent/__init__.py
dmcontent/content_loader.py

* Drop everything except letters and numbers (regex \w) from ids/names before generating the slug.
* Bump version to 5.3.1

Drop everything except letters and numbers before generating slugs

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

For [this pivotal story](https://www.pivotaltracker.com/story/show/141314099)
Before version 3.0.0 of the content loader, for dynamic lists we were dropping followup fields if the followup question had been answered `False` as such:
```
for question in self.questions:
if question.get('followup'):
if q_data.get(question.id) is False:
q_data.pop(question.followup, None)
```
This behaviour was then replaced by the `drop_followups` util method in 3.0.0.
Also note that evidence fields are always sent in a POST request as they are textareas even if they are empty but radio buttons are not if unanswered.
For the below examples, please look at [the 3.0.0 PR](https://github.com/alphagov/digitalmarketplace-content-loader/pull/25/files) so you can follow along with both 2.9.0 and 3.0.0 for the …

Fix dynamic lists

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_content_loader.py
tests/test_questions.py

This PR fixes a bug in the 'answer_required' property for MultiquestionSummary, caused by a lack of knowledge about questions with followups.
Previously, MultiquestionSummaries would only do the following:
* Check all questions and return True if any of those questions require an answer.
This would cause most questions-with-dependencies to incorrectly return True if the answers given by a user did not provide answers for all questions because some of the questions were not required followups.
To fix this, a MultiquestionSummary will now do three things:
* If the multiquestion itself is marked as optional, return False.
* Iterate over all questions that have followups. For each one, if it requires answer return True. If it doesn't, check whether each of its followup are 1) required (i.e. …

Fix unanswered questions count

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

Story https://www.pivotaltracker.com/story/show/141943157
It's useful to be able to properly test whether a key is present in the `_data` - `.get()` doesn't allow you to distinguish between an absent key and a present key with a `None` value.

[#141943157]Question: implement `__contains__`

---

CHANGELOG.md
dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/questions.py
requirements.txt
setup.cfg
setup.py
tests/test_content_loader.py
tests/test_questions.py

* Create a new `Date` class for handling date questions.
* Create a new `DateSummary` class for handling viewing dates in summary tables etc.
* Register `Date` handler in `QUESTION_TYPES` to make it auto used by all date type questions.
* Tests.
https://trello.com/c/G3J4fbtw/30-add-question-type-to-content-loader-and-summary-display

141882981-Add-question-type-to-content-loader-and-summary-display

---

dmcontent/__init__.py
dmcontent/questions.py
dmcontent/utils.py
tests/test_utils.py

- will also be used by script in the frameworks API (for generating Elasticsearch mappings).
https://trello.com/c/etYh34Zs/341-fixing-software-parent-categories

Tiny utility function for getting checkbox option values.

---

requirements.txt
setup.py

Add dm-utils dependency to setup.py, as well as requirements.txt:
- required so that apps dependent on the Content Loader fail clearly if they do not already have dm-utils in _their_ requirements.txt.

Fix missing dm-utils dependency

---

dmcontent/__init__.py
dmcontent/content_loader.py
tests/test_content_section.py

Provide easy way to determine if an entire section is empty
- Empty sections shouldn't show on the service page for buyers
- An empty section is any section where none of the answers have been
filled out.
https://trello.com/c/9mmLtRCC/352-questions-with-dependencies

Content loader for service page

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

Adds a `filter_value` property to question summaries that will replace values with their `filter_label` from content if it exists, or fall back to the usual value otherwise.

Add filter label values to question summary

---

CHANGELOG.md
dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/questions.py
tests/test_content_loader.py
tests/test_questions.py

Some of our declaration questions want to be able to reference other questions, so that we can say things like 
```if you answered question 32, you have to answer this one```. 
The syntax they use for this is a bit peculiar. It looks like 
```if you answered question [[questionId]], you have to answer this one```.
I'm trying to get rid of this, in favour of something like
```if you answered question {{ content.get_question('questionId').number }}, you have to answer this one.```
Since v2 of the Content Loader, we can [use jinja to render `TemplateField`s](https://github.com/alphagov/digitalmarketplace-content-loader/blob/master/CHANGELOG.md#200).  The fields we allow to be templated are whitelisted -- for example, `question` and `hint` accept jinja templating, but `type` and `id` don't. …

Make validation messages into TemplateFields

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

https://trello.com/c/PHnolEgP/16-change-money-format-on-awarding-a-brief-to-be-pounds-and-pence
Users had previously been able to say that a contract was worth £8.105. This should not be allowed. Instead we only allow 0 or 2 decimal places e.g £8 or £8.10 to be stored in the database. This new content loader property can be used by the frameworks repo to know when to use the stricter format for `pricing` questions and generate the new JSON schemas for them.
In addition, we make the validation permissive so if a user enters '10.0' or '10.', it will be transformed into '10.00' and their price will validate rather then forcing them to type their answer in the exact format we require. 
See frameworks repo PR for further details - https://github.com/alphagov/digitalmarketplace-frameworks/pull/4 …

Add ability to set pricing question decimal place restriction

---

dmcontent/__init__.py
requirements.txt
setup.py

The content loader repo currently requires v.25.1.0 of the `digitalmarketplace-utils` library. This version has an outdated dependency on `cryptography` package that is not compatible with Python3, meaning we are unable to build an environment or run tests against the content loader.
This PR bumps the DM utils dependency to v30.0.0. That's 5 major versions, but I'm confident that this shouldn't introduce breaking changes. The content loader only uses `dmutils` in two places: date formatting and the `DMSandboxedEnvironment`, neither of which have changed since v25.1.0. 
Please let me know if I've missed anything that means this upgrade should be 5.0.0 instead of 4.7.0!

Upgrade DM utils dependency

---

dmcontent/__init__.py
requirements-dev.txt
setup.cfg
tests/test_formats.py

Good news: Following the upgrade of the content loader (https://github.com/alphagov/digitalmarketplace-content-loader/pull/49), we can now run tests. 
Bad news: there are some pytest deprecation warnings. This PR fixes them.

Fix pytest warnings

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

Trello ticket: https://trello.com/c/77L1kwqj/28-2-list-of-errors-in-header-in-incorrect-order-for-brief-weighting-question
The content loader was returning errors for multi-part questions in alphabetical order. This fix returns them in the same order as the questions (see below for example).
~~I opted for a major version bump as this is likely to break any tests that assert error messages as a list - if I'm being overcautious I'm happy to downgrade to a minor bump!~~ Going for a minor bump as discussed below.
```
>>> question = ContentQuestion({"questions": [{"id": "technicalCompetence", ...}, {"id": "culturalFit", ...}])
>>> question.get_error_messages({"technicalCompetence": "an error happened", "culturalFit": "another error happened"})
OrderedDict([
("culturalFit", {"message": "an …
```

Fix multi question ordering

---

dmcontent/__init__.py
dmcontent/utils.py
tests/test_utils.py

Add a util method to try loading a manifest in an application. The tests might be controversial as they literally just check what the method is doing internally, but that feels like the right thing to do in this case I think the contract this method makes is simply that another method is called - what that method itself does shouldn't be tested here, I don't think.
Bump version to 4.9.0
https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/68
https://trello.com/c/tnBdllTV/156-briefs-frontend-has-crashed-on-preview-wont-come-back-up

Add 'try_load_manifest' generic method for apps.

---

dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/metadata.py
setup.py
tests/test_content_loader.py
tests/test_metadata.py

We need to be able to copy services from one framework to another during
applications to save suppliers time. In order to do this, we need to
define which previous framework has services that are eligible for
copying, and which questions are suitable. This information appears to
be data related to the framework, so we are storing it in dm-frameworks
as metadata about a given framework (in this case, G-Cloud 10). In order
for a frontend to have that information, we need to be able to load it.
The `messages` folder of dm-frameworks stores files that contain
key-value pairs, and this is the same kind of information format we want
for our metadata, so this creates a stripped-down version of the same
which works on the `metadata` folder of a framework. A ContentMetadata
instance does not parse …

Load arbitrary framework metadata

---

dmcontent/__init__.py
dmcontent/utils.py
setup.py
tests/test_utils.py

For [this trello ticket.](https://trello.com/c/LjbF4cLc)
We have an existing util for handling exceptions when loading a
manifest. Versions of this for messages and metadata would also be
useful.
It'll help when loading content in `app.__init__.py` by saving having
conditionals for different framework versions.

Add util functions for trying to load metadata and messages

---

README.md
dmcontent/__init__.py

Adds a nifty visual indicator of what versions of Python we support
Part of https://trello.com/c/wWFsv1SU/230-be-clear-in-our-libraries-what-versions-of-python-we-support

Add a Python version badge to README

---

dmcontent/__init__.py
setup.py

Add python_requires specification to setup.py that explicitly declares which versions of Python this library supports/is tested on.
Part of https://trello.com/c/wWFsv1SU/230-be-clear-in-our-libraries-what-versions-of-python-we-support

Support Python 3.6 only

---

default.nix
requirements-dev.txt

default.nix: ensure venv is created relative to default.nix, not cwd

---

dmcontent/__init__.py
requirements.txt
setup.py

Also remove direct werkzeug dependency - we should be able to rely on flask including werkzeug and this library's use of it isn't tremendously version specific.
I've tested this version against both `44.0.1` and `48.2.0`.
Kept the upper limit of `-utils` versions, bumping it to `<49`, just so we get prompted to re-test it in the future.

Bump -utils dependency

---

CHANGELOG.md
dmcontent/__init__.py
dmcontent/utils.py

https://trello.com/c/RW2tzjbM
Being able to deepcopy a full `ContentLoader` tree gives us a fast way of generating independent `ContentLoaders` for each local context. This approach cheats slightly my transforming the way we hold a reference to a jinja `Template` to be immutable, and therefore not actually _requiring_ a copy. This also means we can _share_ the jinja `Templates` associated with `TemplateField`s, which seem to be the most memory hungry and construction-time hungry parts of a `ContentLoader` tree.
I'm probably being a bit over-cautious in making this a major version bump. I don't think anything touches the internal `template` attribute of a `TemplateField`.

TemplateField: make this deepcopy-able

---

CHANGELOG.md
dmcontent/__init__.py
setup.py

https://trello.com/c/51brdJKx/1201-upgrade-pyyaml-to-5x
I've been cautious and made this a major bump, in case anyone was thinking of using this with an older version of Python.
We are careful to use `yaml.safeload()` instead of the vulnerable `yaml.load()`, but this version of PyYAML deprecates the latter completely so it's no longer even an option 😸

Upgrade PyYAML to 5.x

---

dmcontent/__init__.py
setup.py

https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
The ~= syntax denotes we don't fully support higher versions yet:
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
See equivalent PRs for utils, API client and test utils:
https://github.com/alphagov/digitalmarketplace-utils/pull/544
https://github.com/alphagov/digitalmarketplace-apiclient/pull/225
https://github.com/alphagov/digitalmarketplace-test-utils/pull/25

Remove upper restriction on Python versions

---

dmcontent/__init__.py
dmcontent/utils.py
tests/test_utils.py

We need to use this in the admin frontend for https://trello.com/c/g5P0RxQn and it makes more sense to have this in the content loader than `-utils`. I did look at making it a nice useful method of `ContentManifest` but it would be weird having a method that only works for a certain subset of `ContentManifest`s and you'd only find out if it worked once it dug into the questions it contained... meh.

utils: transplant count_unanswered_questions from supplier frontend

---

dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/messages.py
dmcontent/questions.py
tests/test_content_loader.py
tests/test_content_section.py
tests/test_messages.py
tests/test_questions.py

https://trello.com/c/ooTuJDCw
On my machine,when using the `inplace_allowed` options, this runs the test workload mentioned in https://trello.com/c/RsEEo4So in about 0.59x the time current `master` does.
The bulk of the speedup here comes from new `inplace_allowed` options for `.filter()` and `.summary()`. I'd previously observed that a lot of the time spent in the content loader during normal usage patterns is spent performing deep copy upon deep copy of itself. Currently `.filter()` and `.summary()` calls will return an altered deep-ish copy of themselves ("deep-ish" because it's worse in some places than others). An extremely common usage pattern of the loader however is to call e.g.
```
content_loader.get_manifest("foo").filter(service).summary(service)
```
with each of …

performance improvements, largely through addition of "inplace_allowed" options

---

dmcontent/__init__.py
dmcontent/markdown.py
dmcontent/utils.py
tests/test_utils.py

https://trello.com/c/scaNu2Aq
What do people think? To me, doing this seems less scary than keeping half of our content fields as fully-escaped html.
~Haven't tried this in a frontend yet.~

markdown: add GOVUKFrontendExtension to apply govuk-frontend classes to generated elements

---

dmcontent/__init__.py
dmcontent/html.py
requirements.txt
setup.py
tests/test_html.py

https://trello.com/c/CXGExCLO/55-3-replace-summary-table-with-summary-list-on-g-cloud-service-page-and-dos-opportunity-page
We want to be able to easily display users answers to questions using
the [summary list component](https://design-system.service.gov.uk/components/summary-list/) from the GOV.UK Design System.
To be able to do this we need to turn a collection of QuestionSummary
objects into an list of row objects usable with the `govukSummaryList`
macro.
To achieve this, we have added the `html` module which formats `QuestionSummary` values into HTML and arranges them into a list that can be passed straight into a `{{ govukSummaryList 
rows={transformed_data} }}` macro.

Add html module to format questions for display

---

dmcontent/__init__.py
dmcontent/html.py
tests/test_html.py

Adds missing functionality from digitalmarketplace-frontend-toolkit[1].
We need this for alphagov/digitalmarketplace-buyer-frontend#1041.
[1]:https://github.com/alphagov/digitalmarketplace-frontend-toolkit/blob/v36.1.0/toolkit/templates/summary-content.html#L24-L32

Fix to_html to return text instead of list for one item lists

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

https://trello.com/c/qUAR9Nm4/20-1-replace-validation-banner-with-govuk-frontend-error-summary-component-in-the-briefs-frontend

Add href to question objects to fix error summary links

---

dmcontent/__init__.py
dmcontent/html.py
tests/test_html.py

Fixing the functional tests for alphagov/digitalmarketplace-buyer-frontend#1041 with @gidsg we found a change between staging and preview with DOS opportunity details: currently (on production and staging) optional questions that aren’t answered are shown as empty, whereas with the new version (on preview) optional questions that aren’t answered aren’t shown at all.
---
New behaviour on preview, hiding unanswered questions:
Old behaviour on staging and production, showing unanswered questions as empty:
---
@fajerq decided we should restore the old behaviour.
This PR adds a keyword arg `filter_empty` to `to_summary_list_rows` that when `False` will leave unanswered questions in, restoring the old behaviour.

Add option to not filter empty answers from summary list rows

---

dmcontent/__init__.py
dmcontent/html.py
tests/test_html.py

On the [Briefs FE preview Brief page](https://github.com/alphagov/digitalmarketplace-briefs-frontend/blob/13a289f2387697f3139158bc2b16b46771b1742f/app/templates/buyers/preview_brief_source.html#L123), we use the property `open_links_in_new_tab`, which we hadn't accounted for.
This adds that property to the HTML script.
Required for https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/321
https://trello.com/c/BpDhnaYa/93-1-preview-dos-opportunity-before-publishing

Add new tab link option to to_summary_list_rows

---

dmcontent/__init__.py
dmcontent/markdown.py
requirements-dev.txt
tests/test_utils.py

https://trello.com/c/X4vKC3Bv/112-2-apply-govuk-frontend-styles-to-frameworks-content-for-the-create-a-dos-opportunity-journey
Expands the existing class that adds the `govuk-` classes to paragraphs and lists. We now add classes to update `<a>` and `<h2>` for markdown content in the frameworks repo. 
We're consistently using `govuk-heading-l` for `<h1>` and `govuk-heading-m` for `<h2>` for non-frameworks content across the apps.

Add govuk-heading and govuk-link classes to anchor and h2 elements

---

dmcontent/__init__.py
dmcontent/html.py
dmcontent/questions.py
tests/test_html.py

https://trello.com/c/YF7l0YY3/169-3-replace-summary-tables-in-the-create-dos-opportunity-journey-with-summary-lists
The above ticket requires action links on the summary table which is currently not supported. This PR creates a new method `to_summary_list_row` which defines the logic for introducing these action links.
This is required for https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/336

Add to_summary_list_row method

---

dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/questions.py
tests/test_content_loader.py

We're having issues where the question advice is sometimes wrapped in HTML `p` tags, and sometimes isn't.
Ideally it would be consistent, so this commit changes the behaviour of the content loader to always treat the `question_advice` field as Markdown.  This means it will always be HTML `<p>`s!

Change Question.question_advice to be always Markdown

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
dmcontent/questions.py
requirements-dev.in
requirements-dev.txt
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

This is my contribution to https://trello.com/c/YXsBOrDK/110-3-replace-text-boxes-with-govuk-frontend-text-input-component-in-create-a-dos-opportunity-journey. It tries to suggest a way forward for creating govuk-frontend forms from content loader objects.
The basic approach is to move almost all of the logic into Python code. I've put this logic into the content loader repo in this PR, so it can be more easily tested and type-checked (and perhaps one day more easily deleted!). This contrasts to the approach that digitalmarketplace-frontend-toolkit took; all of the formatting and dispatch logic that used to be in the macros `digitalmarketplace-frontend-toolkit/templates/forms` should (in my opinion) live in this module. The benefit of this is easier testing, as well as (in my opinion) …

Add dmcontent.govuk_frontend for creating govuk-frontend components from Question objects

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

https://trello.com/c/VG4caYdJ/136-3-replace-list-form-with-list-input-component-in-create-a-dos-opportunity-journey
For Questions of type "list", we use the new List Input component.
Because this uses a fieldset legend as the question heading, we have less flexibility in where we can place it since it must wrap around its fields. 
Because we can alter List Input to suit our needs, we can simply account for question advice within the component itself. (See https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/163).
GOVUK components like Checkboxes will be trickier to handle, but I've left that as out of scope for this ticket.
This is for use on the Briefs FE: https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/339

Add List Input to dmcontent.govuk_frontend

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

For multiquestions, we don't want each child's label/legend to be set as the page heading, so we need a way to flag this.
This enables the is_page_heading property to be set as appropriate.

Add is_page_heading property

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/test_govuk_frontend.py

Previous checks could result in params["value"] being set to "None", which would display on elements such as textarea.
This change means the value param doesn't even get created in this case.

Fix checks for question.id

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
requirements.txt
setup.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

Ticket: https://trello.com/c/6xOXfwx7/123-2-use-radios-component-for-radios-questions-in-create-a-dos-opportunity-journey
This adds `govuk_radios` to create params for govukRadio from Question objects, and updates `from_question` to handle that question type.
This uses the [function `govuk_options` from dmutils](https://github.com/alphagov/digitalmarketplace-utils/blob/79cbc5eac674cb438fc90c598b76395f50491a25/dmutils/forms/helpers.py#L70) to do most of the work (thanks @agalamatis!).
It doesn't support questions with type boolean or items with conditionally revealing content, but as we don't use those in the create a DOS opportunity journey I considered that out of scope.

Add support for radios questions to dmcontent.govuk_frontend

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

https://trello.com/c/xHVb6nOe/117-2-replace-textarea-component-in-create-a-dos-opportunity-journey
This implements govuk_character_count to generate params for a [govukCharacterCount](https://design-system.service.gov.uk/components/character-count/).
Since we only use maximum word count on the DOS Opportunity journey, this ticket is scoped to that - maximum character count is left as out of scope.

Add character count to dmcontent.govuk_frontend to create params from Question objects

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

https://trello.com/c/zx1hJsgX/114-2-replace-checkboxes-in-create-a-dos-opportunity-journey
Builds on the work done in #97, adding `govuk_checkboxes` to create params for govukCheckboxes from Question objects, and updates `from_question` to handle that question type.

Add support for checkboxes questions to dmcontent.govuk_frontend

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

https://trello.com/c/k2SADNQr/172-2-replace-date-input-component-in-create-a-dos-opportunity-journey
Adds govuk_date_input to create params for govukDateInput from Question objects, and updates from_question to handle that question type.
We don't currently do granular error checking for date inputs, and this component reflects that. The [Design System component](https://design-system.service.gov.uk/components/date-input/) does recommend error messages are specific, but I think that's out of scope for this ticket.
Bumped version to 7.18 because the checkboxes PR (#98) is ready to go and I'll merge that first as 7.17.

Add support for date questions to dmcontent.govuk_frontend

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

If a question legend is not the page heading, we were defaulting to no sizing class on the fieldset legend. This ensures we apply a default legend style.

Add fieldset heading class for fieldset legends in multiquestions

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

Ticket: https://trello.com/c/0cIr1131/210-2-replace-number-type-questions-in-create-a-dos-opportunity-journey
We can now use GOV.UK Frontend text input components for number questions.

Add support for number questions to govuk_frontend.from_question

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

We want to make sure the inputs are all the same height in our apps.

Add height compatible override class to date input inputs

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

https://trello.com/c/oIEbMdvM/213-2-replace-pricing-type-questions-in-create-a-dos-opportunity-journey
This only handles the case where the pricing question has a single field `price`, as this is the only case found in the briefs frontend. However I've taken some care to make sure the design will extend to the multiple fields case.
Like with the number field, this commit includes the params for a prefix, but they won't show up until https://github.com/alphagov/govuk-frontend/issues/1915 is closed.

Add dm_pricing_input to govuk_frontend

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
dmcontent/questions.py
tests/test_questions.py

If an app is using govuk-frontend version 3 and up we don't want the href to end with a `-1`, as that is not what the template will output.
To use this an app should set `dmcontent.govuk_frontend.govuk_frontend_version` at some point early on in the loading process.

Add feature flag to Question to change behaviour of href

---

dmcontent/__init__.py
dmcontent/formats.py
dmcontent/questions.py
tests/test_formats.py
tests/test_questions.py

Trello: https://trello.com/c/yWkgqyPL/325-2-update-dos5-application-content-in-the-frameworks-repo
In DOS 5, we will only have the maximum. Update the summary so this gets handled correctly. Add tests to verify. Add in some type hints for fun.
I am assuming that nothing that currently exists relies on the previous behaviour. As far as I can tell, form verification ensures that the minimum is provided where it is needed.

Add support for pricing without minima

---

dmcontent/__init__.py
dmcontent/formats.py
tests/test_content_loader.py
tests/test_formats.py
tests/test_questions.py

Trello: https://trello.com/c/yWkgqyPL/325-2-update-dos5-application-content-in-the-frameworks-repo
As [recommended](https://trello.com/c/WlpUAQZe/327-1-update-supplier-fe-content-for-dos5-application-journey#comment-5f64a5e2b98036851c51ea1b) by the recent accessibility review. Matches changes already made in https://github.com/alphagov/digitalmarketplace-frameworks/pull/635

Replace 'per' with 'a'

---

dmcontent/__init__.py
requirements-dev.txt
requirements.txt
setup.py
tests/test_markdown.py

We want to be able to keep up to date with [Python-Markdown](https://pypi.org/project/Markdown/), which is currently on version 3.3. Currently however we are constrained to use the latest 2 series version, which was released in 2018.
This PR adds tests to our Markdown extension so we can be sure nothing will break from upgrading, and lifts the upper bound on the requirement constraint.
This PR does not change the extension (although it uses some deprecated APIs) because that would be a breaking change, which we don't want right now.

Update Markdown requirement to latest major version

---

dmcontent/__init__.py
dmcontent/converters.py
dmcontent/questions.py
tests/test_converters.py
tests/test_questions.py

Ticket: https://trello.com/c/MwEMI2pR/428-fix-the-problem
We want to be able to gracefully handle the case where users input units into a form, following Design System guidance [[1]].
Now number type questions with a unit will be automatically filter those units from the user data.
The code to remove prefixes or suffixes is copied from [PEP-616][2], one day we might be able to replace it with the `removeprefix()` and `removesuffix()` methods.
[1]:
https://design-system.service.gov.uk/components/text-input/#prefixes-and-suffixes
[2]: https://www.python.org/dev/peps/pep-0616/

Add remove prefix/suffix support to number type questions

---

dmcontent/__init__.py
dmcontent/formats.py
tests/test_formats.py

Add commas to the prices for G-cloud services so they're easier to read, and bump the minor version number
Addresses https://trello.com/c/UL5WzBD7/1412-add-commas-to-price-formatting-on-g-cloud-service-pages

Add commas to price formatting for G-Cloud services

---

.travis.yml
dmcontent/utils.py

And fix a DeprecationWarning: "Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working"

Start testing against Python 3.9

---

dmcontent/__init__.py
dmcontent/formats.py
tests/test_formats.py

Trello: https://trello.com/c/RlNy5WlG/2074-ccsrequests-re-listing-correction
Previously, we always used 'a'. This doesn't work for things like 'a instance', and a supplier has noticed this. Fixing this properly will be a bit involved. So add a heuristic that should work most of the time.
If this is not enough, we should just use inflect rather than trying to write code that understands english better than this.
This is hacky as all heck, so I've included a comment to try and explain this monstrosity to future devs.

Choose whether to use 'a' or 'an'

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/test_govuk_frontend.py

https://trello.com/c/13tOvxuu/285-2-replace-content-loader-form-macros-in-brief-responses-frontend
digitalmarketplace-frontend-toolkit uses `boolean` questions, which are yes/no inline radio inputs:
We don't currently handle them with govuk_frontend, but our work on `brief-responses` has uncovered some:
`yesNo`
`essentialRequirementsMet`
We can simply use `govukRadios` and add `govuk-radios--inline` to the `classes` property to achieve the effect in govuk-frontend.

Add boolean to govuk_frontend

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/test_govuk_frontend.py

https://trello.com/c/13tOvxuu/285-2-replace-content-loader-form-macros-in-brief-responses-frontend
During testing on Brief Responses, I discovered that boolean questions don't have an `options` property, and so fail.
This fixes that by setting the options property.

Add options to boolean question

---

README.md

...since switching to Github Actions

remove coveralls badge as we don't use it anymore

---

dmcontent/__init__.py
dmcontent/questions.py
tests/test_questions.py

Is DOS5 the first question when submitting a brief response is a date question, so the brief response has no data at that point. 
Also move unformat test with no data to base class so we know all subclasses of `Question` can handle the case with no data.

Allow date questions to unformat when there is no data

---

.flake8
dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/test_govuk_frontend.py

Ticket: https://trello.com/c/fu3k1QO7/290-3-replace-content-loader-questions-with-followup-in-brief-responses-frontend
`render()` is a Python replacement for the [`show_question.html`][1] template that has developed to handle the output of `from_question()`.  While `show_question.html` is working for most cases, it has a couple of downsides
1. we have it repeated across all frontend repos where it's needed
2. it can't handle complex forms such as radios with conditionals
3. it's code is a little bit repetitive
This commit aims to address those problems by moving the logic to show a question into `dmcontent` where it can be shared across all apps, and by rewriting it in Python that should also make it possible to do more complicated things in future.
Currently `render()` is a bit more …

Add `govuk_frontend.render_question()` for calling govuk-frontend macros from Python

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/test_govuk_frontend.py

Fixes a bug I found while trying to bump dmcontent in alphagov/digitalmarketplace-briefs-frontend#379.

Fix behaviour of render_question with unrecognised question type

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

Ticket: https://trello.com/c/YG2SH78x/751-3-add-support-for-multiquestions-to-dmcontentgovukfrontend
We want to be able to render multiquestions using `govuk_frontend.render_question()`. This PR adds support for simple multiquestions (no followup/conditionally revealed content).
https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/383 shows an example of this in an app.

Add support for multiquestion to dmcontent.govuk_frontend

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

Ticket: https://trello.com/c/cMtAeSL2/764-3-add-support-for-conditionally-revealed-content-to-dmcontentgovukfronted
We want to be able to handle multiquestions that contain questoins with followups, like DOS5's [niceToHaveRequirements and yesNo questions][1]. The Design System calls this [conditionally revealing content][2].
This PR adds logic to `dm_multiquestion()` to handle these questions.
We put the logic here rather than in say `govukRadios()` because a) the way followups currently work is a little confusing, and b) it would be better in the long term to re-evaluate how we lay out these questions for the user and define them in the framework manifests. For now this commit gives us some form of backwards compatibility to unblock migration to govuk-frontend.
This does change how these …

Add support for followup questions in multiquestions

---

dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/questions.py

https://trello.com/c/9RUq5TL8/1243-2-bug-emessage-passed-to-inappropriate-error-handler
We have previously introduced bugs by passing the wrong type in. Add type hints to make this mistake harder to make in future.

Add type hints to `get_error_messages`

---

dmcontent/__init__.py
dmcontent/content_loader.py
dmcontent/utils.py
tests/test_content_loader.py
tests/test_utils.py

Manifests are slow to load - they take ~1 second each. This contributes to very slow app startup times - ~20-30 seconds for supplier-frontend.
Many of the manifests are for old frameworks that are requested very rarely or not at all. Thus, we can lazily load these old frameworks to give us a speedup on app startup without significantly slowing down real users.
See alphagov/digitalmarketplace-supplier-frontend#1348 for the experimental version of this I used for testing. Based on the numbers in that PR, I think this will save developers a few minutes per day of waiting for tests, which will add up significantly over the course of a year.
Note that the LazyDict created for this purpose is not thread safe. This is not a problem. The worst that could happen is that two threads simultaneously …

Allow lazy loading of manifests 

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

We want to use the `govukFileUpload` component[[1]] for our questions with `type: upload`[[2]].
Add a branch to `render_question` that generates parameters suitable for this component.
https://trello.com/c/7Hw9pH6X/855-2-add-type-upload-to-content-loader-renderquestion
[1]: https://design-system.service.gov.uk/components/file-upload/
[2]: https://github.com/alphagov/digitalmarketplace-frameworks/blob/a691598f98aa4a21c2615bdc07437898abe1591e/frameworks/digital-outcomes-and-specialists-5/questions/declaration/modernSlaveryStatement.yml

Add support for file upload questions

---

dmcontent/__init__.py
dmcontent/markdown.py

You now can use markdown h3 syntax in template content.

Add h3 to markdown.GOVUKFrontendExtension

---

dmcontent/html.py
requirements-dev.in
requirements-dev.txt
requirements.txt
tasks.py

So that we can run mypy against this repo to check our types.
Don't add this to `invoke test` because it's currently very broken. Once we've fixed all the errors, we should add it to `invoke test`.
Also fix one wrong type hint I noticed.
This is the current output of `invoke test`:
```
mypy dmcontent/
dmcontent/html.py:22: error: Skipping analyzing 'dmutils.filters': found module but no type hints or library stubs
dmcontent/html.py:22: error: Skipping analyzing 'dmutils': found module but no type hints or library stubs
dmcontent/utils.py:7: error: Skipping analyzing 'dmutils.jinja2_environment': found module but no type hints or library stubs
dmcontent/govuk_frontend.py:54: error: Skipping analyzing 'dmutils.forms.errors': found module but no type hints or library stubs …
```

Add 'invoke test-mypy' command

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

The question [modernSlaveryTurnover](https://github.com/alphagov/digitalmarketplace-frameworks/blob/main/frameworks/digital-outcomes-and-specialists-5/questions/declaration/modernSlaveryTurnover.yml) contains multiple, un-nested conditional questions.
We've (probably sensibly) allowed for only one conditional question.
This PR allows the `dm_multiquestion` function to create a list of conditional questions, and handles this case in the `render` function.
I've flagged this question as one which may benefit from some UR: https://trello.com/c/JPQmbdfD/9-better-way-of-handling-the-modern-slavery-question

Allow for multiple conditional questions

---

dmcontent/govuk_frontend.py

Trello: https://trello.com/c/DZ28pqhm/90-try-to-add-type-hints-to-content-loader
Content loader is quite complex. We'd like to use mypy to check that we're not doing anything wrong. This PR is a pre-requisite that fixes the existing mypy failures in `dmcontent/govuk_frontend.py`.
We've not changed the type signature or behaviour of any methods used by the frontend apps. So this should have no effect outside this repo.
See individual commits for details of what (and why) this PR does.

Fix type hints in dmcontent/govuk_frontend.py

---

dmcontent/content_loader.py

Trello: https://trello.com/c/DZ28pqhm/90-try-to-add-type-hints-to-content-loader
Content loader is quite complex. We'd like to use mypy to check that we're not doing anything wrong. This PR is a pre-requisite that fixes the existing mypy failures in `dmcontent/questions.py`.

Fix type hints in dmcontent/content_loader.py

---

dmcontent/questions.py
tests/test_questions.py

Trello: https://trello.com/c/DZ28pqhm/90-try-to-add-type-hints-to-content-loader
Content loader is quite complex. We'd like to use mypy to check that we're not doing anything wrong. This PR is a pre-requisite that fixes the existing mypy failures in `dmcontent/questions.py`.
This is slightly more complex than #146 in that we've used `TypeVars` to show that methods on the base classes can be called by subclasses and return the type of the sub class. This is similar to the way typing is done for generics - the [mypy docs](https://mypy.readthedocs.io/en/stable/generics.html) have a pretty good explanation.
See individual commits for details of what (and why) this PR does.

Fix type hints in dmcontent/questions.py

---

CHANGELOG.md
dmcontent/__init__.py
requirements.txt
setup.py
tasks.py

Trello: https://trello.com/c/DZ28pqhm/90-try-to-add-type-hints-to-content-loader
As per [PEP 561](https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages), we need to let type checkers know that this package has type hints. We do this by adding an empty `py.typed` file, and adding it to `setup.py`.
mypy will now recognise that this package is typed. So it will check the types when type checking things that depend on `dmcontent`.
Very similar to https://github.com/alphagov/digitalmarketplace-utils/pull/606

Mark this package as having type hints

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py

`dmListInput` requires `maxItems` to be defined in order to render the correct number of inputs.
On Supplier Frontend, we have some questions that do not define `number_of_items` since the Frontend Toolkit forms macro passed a default of 10 into the old List Entry component.
Rather than hunting down all the questions that do this and adding `number_of_items` to each, we can pass the same default here.

Add default max items for list input

---

dmcontent/__init__.py
dmcontent/content_loader.py

We use the digitalmarketplace-content-loader `render_question` method  to render forms across our frontend apps.
This method expects a single question as input, but in some cases we're using `get_question_as_section` to convert
Questions to ContentSections. This has the side-effect of removing information about the question itself. For
example, we lose the `type` property.
To deal with this, we've created a new method which retains this question information so that we can access it normally.

Add get_question_as_section_containing_itself

---

dmcontent/__init__.py
dmcontent/markdown.py
tests/test_markdown.py

Fix a bug where invalid HTML was generated when a HTML list was put in one of a question's Markdown fields (eg. `essentialRequirementsMet`[1])
This was because the markdown preprocessor (`markdown.preprocessors.HtmlBlockPreprocessor`) replaces raw HTML content with a placeholder value wrapped in an empty `<p></p>`. There is a postprocessor (`markdown.postprocessors.RawHtmlPostprocessor`) that finds the placeholders and removes the empty `<p></p>`, however we have a custom [`Treeprocessor`](https://github.com/alphagov/digitalmarketplace-content-loader/blob/main/dmcontent/markdown.py#L8) which added on the `govuk-body` class to these empty `<p>` tags and meant that they weren't removed by the post processor.
This meant that we had list elements wrapped in `<p>` tags in the output HTML which …

Fix bug when generating list HTML

---

requirements-dev.txt
requirements.txt

There are a few dependencies that were getting a bit old. This was because they could only be upgraded together. This meant that Dependabot couldn't cope, because it wants to only upgrade one thing at a time.
Fixes a moderate-severity issue reported by Dependabot: https://github.com/alphagov/digitalmarketplace-content-loader/security/dependabot/requirements.txt/urllib3/open

Unblock upgrade of urllib3

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
tests/__snapshots__/test_govuk_frontend.ambr
tests/test_govuk_frontend.py

In some cases, we may pass 0 in a govukInput field and expect it to be a valid answer.
This doesn't display as Jinja evaluates 0 as falsy in the template: https://github.com/alphagov/govuk-frontend/blob/b2687fe47f3eb37d8790f422edb520fc24b4e0cd/src/govuk/components/input/template.njk#L51
We can fix this by stringifying `int`s for govukInputs, since we're using an input of `type='text'` anyway.

Fix bug when number field value is 0

---

dmcontent/__init__.py
dmcontent/govuk_frontend.py
setup.py
tests/test_govuk_frontend.py
tests/test_questions.py

https://trello.com/c/oWvOqn00/2276-upgrade-to-flask-v2
We'd like to be able to upgrade to Flask 2.0 because it promises performance improvements that might be handy to us.
Fix up some minor typing problems caused by Flask 2.0. We'll be able to fix it all up properly once we drop support for Flask 1.0.
I've tested that this works fine with both Flask 1.x and 2.0

Add support for Flask 2.0

---

dmcontent/utils.py

> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

Fix collections deprecation
